### ISSUE TITLE
Recall@1 for MoCo

### ISSUE THREAD

**Issue by jh072535** [tjddus9597/STML-CVPR22#3]
Thanks for your sharing! However, as I repeat your work of MoCo, I found the max Recall@1 value is 0.013, could you explain this phenomenon. Thank you!
![1](https://github.com/tjddus9597/STML-CVPR22/assets/59907813/4d36cf2c-cdb3-4a90-a315-bdaeb1c65b7f)

**Comment by sung-yeon-kim** [comment]
Experiments of self-supervised learning methods including MoCo in Table 4 used a model pre-trained on ImageNet like the same setting of Table 1.
Seeing that Recall@1 is close to 0, I suspect you are not using pre-trained weights.
I recommend that you change the settings of your experiment. 
If you have any other questions, please leave a comment.

**Comment by jh072535** [comment]
Thanks for your reply! I follow your setting, I found that if choose the "SOP" dataset, it will normally output the same result like your paper. But as I choose the "cars" dataset, the Recall@K will turn to extremely low like former question. But I did not change your code.

**Comment by sung-yeon-kim** [comment]
The CUB and Cars datasets are very small in size, making it difficult to train a scratch model and easily overfit. 
On the other hand, SOP has a dataset size large enough to train without a pre-trained weight, which is why we conducted scratch experiments only in SOP. And, of course, using pre-trained weights is advantageous in terms of performance even on the SOP dataset.
